KUBOnlinePRPM/Controllers/PMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KUBOnlinePRPM.Controllers
{
    public class PMController : DBLogicController
    {
        // GET: PM
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProjectDetail()
        {
            return View();
        }
        public ActionResult DODetails()
        {
            return View();
        }
        public ActionResult ProjectOverview()
        {
            return PartialView();
        }
        public ActionResult ProjectSchedules()
        {
            return PartialView();
        }
        public ActionResult ProjectFinance()
        {
            return PartialView();
        }
        public ActionResult ProjectDO()
        {
            return PartialView();
        }
        public ActionResult ProjectIssues()
        {
            return PartialView();
        }
        public ActionResult ProjectReport()
        {
            return PartialView();
        }
        public ActionResult ProjectFiles()
        {
            return PartialView();
        }
        public ActionResult ProjectConversation()
        {
            return PartialView();
        }
    }
}

KUBOnlinePRPM/Views/PM/Index.cshtml
<div class="row container-fluid g-mb-20">
    <div class="media-body align-self-center text-left">
        <h3 class="g-font-weight-300 g-font-size-20 g-color-black">Project Portfolio Dashboard</h3>
    </div>
</div>
<div class="row container-fluid g-mb-40">
    <div class="col-md-4 g-mb-30">
        <div class="card card-outline-primary rounded-0">
            <h3 class="card-header h5 text-white bg-primary g-brd-transparent rounded-0">
                <i class="fa fa-tasks g-font-size-default g-mr-5"></i>
                18 Projects
            </h3>
            <div class="card-block">
                <div id="TotalProjects" style="width: 100%; height: 300px;" class="d-lg-inline-block"></div>
            </div>
        </div>
    </div>
    <div class="col-md-4 g-mb-30">
        <div class="card card-outline-primary rounded-0">
            <h3 class="card-header h5 text-white bg-success g-brd-transparent rounded-0">
                <i class="fa fa-tasks g-font-size-default g-mr-5"></i>
                RM 53M revenue
            </h3>
            <div class="card-block">
                <div id="TotalRevenue" style="width: 100%; height: 300px;" class="d-lg-inline-block"></div>
            </div>
        </div>
    </div>
    <div class="col-md-4 g-mb-30">
        <div class="card card-outline-primary rounded-0">
            <h3 class="card-header h5 text-white bg-info g-brd-transparent rounded-0">
                <i class="fa fa-tasks g-font-size-default g-mr-5"></i>
                RM 10M cost
            </h3>
            <div class="card-block">
                <div id="TotalCost" style="width: 100%; height: 300px;" class="d-lg-inline-block"></div>
            </div>
        </div>
    </div>
    <div class="col-md-4 g-mb-30">
        <div class="card card-outline-primary rounded-0">
            <h3 class="card-header h5 text-white bg-danger g-brd-transparent rounded-0">
                <i class="fa fa-tasks g-font-size-default g-mr-5"></i>
                RM 43M gross profile
            </h3>
            <div class="card-block">
                <div id="TotalGP" style="width: 100%; height: 300px;" class="d-lg-inline-block"></div>
            </div>
        </div>
    </div>
    <div class="col-md-4 g-mb-30">
        <div id="TotalContVsClaim" style="width: 100%; height: 300px;" class="d-lg-inline-block"></div>
        <div id="myDiv" class="container-fluid media-body align-self-center text-center">
            Total Contract VS Amount Claimed
        </div>
    </div>
    <div class="col-md-4 g-mb-30">
        <div id="PlanVsActual" style="width: 100%; height: 300px;" class="d-lg-inline-block"></div>
        <div id="myDiv" class="container-fluid media-body align-self-center text-center">
            Planned VS Actual Cost
        </div>
    </div>
    <div class="col-md-12">
        <div class="card card-outline-primary rounded-0">
            <h3 class="card-header h5 text-white g-bg-primary g-brd-transparent rounded-0">
                <i class="fa fa-tasks g-font-size-default g-mr-5"></i>
                Project by Health
            </h3>
            <div class="card-block">
                <div class="container-fluid row">
                    <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                        <div class="ProjectDetail card h-100 g-brd-black rounded g-line-height-2" role="alert" style="cursor:pointer">
                            <div class="media-body align-self-center">
                                <h4 class="g-font-size-12 g-color-gray-dark-v6 mb-0">KUB Agro</h4>
                            </div>
                            <div class="media align-self-center">
                                <div class="d-flex g-mr-15 g-font-size-12 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                    Project A - good <br />
                                    Project B - have issues
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                        <div class="ProjectDetail card h-100 g-brd-black rounded g-line-height-2" role="alert" style="cursor:pointer">
                            <div class="media-body align-self-center">
                                <h4 class="g-font-size-12 g-color-gray-dark-v6 mb-0">KUBtel</h4>
                            </div>
                            <div class="media align-self-center">
                                <div class="d-flex g-mr-15 g-font-size-12 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                    Project A - good <br />
                                    Project B - have issues
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                        <div class="card h-100 g-brd-black rounded g-line-height-2" role="alert">
                            <div class="media-body align-self-center">
                                <h4 class="g-font-size-12 g-color-gray-dark-v6 mb-0">KUB Power</h4>
                            </div>
                            <div class="media align-self-center">
                                <div class="d-flex g-mr-15 g-font-size-12 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                    Project A - good <br />
                                    Project B - have issues
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                        <div class="card h-100 g-brd-black rounded g-line-height-2" role="alert">
                            <div class="media-body align-self-center">
                                <h4 class="g-font-size-12 g-color-gray-dark-v6 mb-0">KUB A&W</h4>
                            </div>
                            <div class="media align-self-center">
                                <div class="d-flex g-mr-15 g-font-size-12 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                    Project A - good <br />
                                    Project B - have issues
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                        <div class="card h-100 g-brd-black rounded g-line-height-2" role="alert">
                            <div class="media-body align-self-center">
                                <h4 class="g-font-size-12 g-color-gray-dark-v6 mb-0">KUB Gaz</h4>
                            </div>
                            <div class="media align-self-center">
                                <div class="d-flex g-mr-15 g-font-size-12 g-font-weight-300 g-color-gray-dark-v6 mb-0">
                                    Project A - good <br />
                                    Project B - have issues
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="container-fluid row">
            <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                <!-- Panel -->
                <div class="card h-100 g-brd-gray-light-v7 rounded  u-shadow-v1-5 g-line-height-2" role="alert">
                    <div class="card-block g-font-weight-300 g-pa-20">

                    </div>
                </div>
                <!-- End Panel -->
            </div>
            <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                <div class="card h-100 g-brd-gray-light-v7 rounded  u-shadow-v1-5 g-line-height-2" role="alert">
                    <div class="card-block g-font-weight-300 g-pa-20">

                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                <div class="card h-100 g-brd-gray-light-v7 rounded  u-shadow-v1-5 g-line-height-2" role="alert">
                    <div class="card-block g-font-weight-300 g-pa-20">

                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                <div class="card h-100 g-brd-gray-light-v7 rounded  u-shadow-v1-5 g-line-height-2" role="alert">
                    <div class="card-block g-font-weight-300 g-pa-20">

                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-lg-2 col-xl-2 g-mb-20">
                <div class="card h-100 g-brd-gray-light-v7 rounded  u-shadow-v1-5 g-line-height-2" role="alert">
                    <div class="card-block g-font-weight-300 g-pa-20">

                    </div>
                </div>
            </div>
            </div>*@
    </div>
</div>

@section scripts {
    <script type="text/javascript">

        $(function () {
            var TotalProjects = new CanvasJS.Chart("TotalProjects", {
                theme: "light2",
                animationEnabled: true,
                data: [
                {
                    type: "column",
                    dataPoints: [
                        { y: 6, label: "Agro" },
                        { y: 4, label: "KUBtel" },
                        { y: 5, label: "Power" },
                        { y: 7, label: "A&W" },
                        { y: 4, label: "Gaz" }
                    ],

                    //You can add dynamic data from the controller as shown below. Check the controller and uncomment the line which generates dataPoints.
                    //dataPoints: @Html.Raw(ViewBag.DataPoints),
                }
                ]
            });
            TotalProjects.render();

            var TotalRevenue = new CanvasJS.Chart("TotalRevenue", {
                theme: "light2",
                animationEnabled: true,
                data: [
                {
                    type: "column",
                    dataPoints: [
                        { y: 12, label: "Agro" },
                        { y: 10, label: "KUBtel" },
                        { y: 11, label: "Power" },
                        { y: 8, label: "A&W" },
                        { y: 10, label: "Gaz" }
                    ],

                    //You can add dynamic data from the controller as shown below. Check the controller and uncomment the line which generates dataPoints.
                    //dataPoints: @Html.Raw(ViewBag.DataPoints),
                }
                ]
            });
            TotalRevenue.render();

            var TotalCost = new CanvasJS.Chart("TotalCost", {
                theme: "light2",
                animationEnabled: true,
                data: [
                {
                    type: "column",
                    dataPoints: [
                        { y: 2, label: "Agro" },
                        { y: 3, label: "KUBtel" },
                        { y: 1, label: "Power" },
                        { y: 2, label: "A&W" },
                        { y: 2, label: "Gaz" }
                    ],

                    //You can add dynamic data from the controller as shown below. Check the controller and uncomment the line which generates dataPoints.
                    //dataPoints: @Html.Raw(ViewBag.DataPoints),
                }
                ]
            });
            TotalCost.render();

            var TotalGP = new CanvasJS.Chart("TotalGP", {
                theme: "light2",
                animationEnabled: true,
                data: [
                {
                    type: "column",
                    dataPoints: [
                        { y: 9, label: "Agro" },
                        { y: 10, label: "KUBtel" },
                        { y: 10, label: "Power" },
                        { y: 7, label: "A&W" },
                        { y: 8, label: "Gaz" }
                    ],

                    //You can add dynamic data from the controller as shown below. Check the controller and uncomment the line which generates dataPoints.
                    //dataPoints: @Html.Raw(ViewBag.DataPoints),
                }
                ]
            });
            TotalGP.render();

            var TotalContVsClaim = new CanvasJS.Chart("TotalContVsClaim",
	{
	    //backgroundColor: "black",
	    data: [
        {
            type: "doughnut",
            toolTipContent: null,
            dataPoints: [
            { y: 136, indexLabel: "RM 40M" },
            { y: 44, indexLabel: "From RM 53M" }
            ]
        }
	    ]
	});
            convertToHalfDoughnut(TotalContVsClaim);
            TotalContVsClaim.render();

            var PlanVsActual = new CanvasJS.Chart("PlanVsActual",
	{
	    //backgroundColor: "black",
	    data: [
        {
            type: "doughnut",
            toolTipContent: null,
            dataPoints: [
            { y: 54.5, indexLabel: "RM 10M" },
            { y: 125.5, indexLabel: "From RM 33M" }
            ]
        }
	    ]
	});
            convertToHalfDoughnut(PlanVsActual);
            PlanVsActual.render();

            function convertToHalfDoughnut(chart) {
                var sum = 0;
                var dataPoints = chart.options.data[0].dataPoints;

                for (var i = 0; i < dataPoints.length; i++) {
                    sum += dataPoints[i].y;
                }

                dataPoints.splice(0, 0, { y: sum, color: "transparent", toolTipContent: null, highlightEnabled: false });
            }

            $(".canvasjs-chart-credit").addClass("hide");
        });
    </script>
}

KUBOnlinePRPM/Views/PM/NewPM.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NewPM</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

KUBOnlinePRPM/Views/PM/ProjectConversation.cshtml
<div class="media-md align-items-center g-mb-30 container-fluid">
    <div class="d-flex g-mb-15 g-mb-0--md">
        <h3 class="g-font-weight-400 g-font-size-16 g-color-black mb-0 g-pa-20">Project Conversation</h3>
    </div>
</div>
<div class="media-md align-items-center g-mb-30 container-fluid">
    <div class="col-md-12">
        <div class="js-scrollbar g-height-400 g-brd-around g-brd-gray-light-v4 rounded g-pa-20 g-mb-30">
            <!-- Comments -->
            <div class="media g-mb-30">
                <img class="d-flex g-width-60 g-height-60 rounded-circle g-mt-3 g-mr-20" src="../../assets/img-temp/100x100/img7.jpg" alt="Image Description">
                <div class="media-body">
                    <div class="d-flex align-items-start g-mb-15 g-mb-10--sm">
                        <div class="d-block">
                            <h5 class="h6">James Coolman</h5>
                            <span class="d-block g-color-gray-dark-v5 g-font-size-11">June 7, 2017</span>
                        </div>
                        <div class="ml-auto">
                            <a class="u-link-v5 g-color-black--hover g-font-weight-600 g-font-size-12 text-uppercase" href="#">Reply</a>
                        </div>
                    </div>

                    <p>
                        This is where we really begin to visualize your napkin sketches and make them into beautiful pixels. Whether through commerce or just an experience to tell your brand's story, the time has come to start using development languages
                        that fit your projects needs.
                    </p>

                    <ul class="list-inline my-0">
                        <li class="list-inline-item g-mr-20">
                            <a class="g-color-gray-dark-v5 g-color-black--hover g-text-underline--none--hover" href="#">
                                <i class="icon-medical-022 u-line-icon-pro g-pos-rel g-top-1 g-mr-3"></i> 5
                            </a>
                        </li>
                        <li class="list-inline-item g-mr-20">
                            <a class="g-color-gray-dark-v5 g-color-black--hover g-text-underline--none--hover" href="#">
                                <i class="icon-finance-206 u-line-icon-pro g-pos-rel g-top-1 g-mr-3"></i> 1
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="media g-brd-top g-brd-gray-light-v4 g-pt-30 g-ml-40 g-mb-30">
                <img class="d-flex g-width-60 g-height-60 rounded-circle g-mt-3 g-mr-15" src="../../assets/img-temp/100x100/img4.jpg" alt="Image Description">
                <div class="media-body">
                    <div class="d-flex align-items-start g-mb-15 g-mb-10--sm">
                        <div class="d-block">
                            <h5 class="h6">Alberta Watson</h5>
                            <span class="d-block g-color-gray-dark-v5 g-font-size-11">June 7, 2017</span>
                        </div>
                        <div class="ml-auto">
                            <a class="u-link-v5 g-color-black--hover g-font-weight-600 g-font-size-12 text-uppercase" href="#">Reply</a>
                        </div>
                    </div>

                    <p>Now that your brand is all dressed up and ready to party, it's time to release it to the world. By the way, let's celebrate already.</p>

                    <ul class="list-inline my-0">
                        <li class="list-inline-item g-mr-20">
                            <a class="g-color-gray-dark-v5 g-color-black--hover g-text-underline--none--hover" href="#">
                                <i class="icon-medical-022 u-line-icon-pro g-pos-rel g-top-1 g-mr-3"></i> 2
                            </a>
                        </li>
                        <li class="list-inline-item g-mr-20">
                            <a class="g-color-gray-dark-v5 g-color-black--hover g-text-underline--none--hover" href="#">
                                <i class="icon-finance-206 u-line-icon-pro g-pos-rel g-top-1 g-mr-3"></i> 0
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="media g-brd-top g-brd-gray-light-v4 g-pt-30 g-mb-30">
                <img class="d-flex g-width-60 g-height-60 rounded-circle g-mt-3 g-mr-15" src="../../assets/img-temp/100x100/img14.jpg" alt="Image Description">
                <div class="media-body">
                    <div class="d-flex align-items-start g-mb-15 g-mb-10--sm">
                        <div class="d-block">
                            <h5 class="h6">David Lee</h5>
                            <span class="d-block g-color-gray-dark-v5 g-font-size-11">June 7, 2017</span>
                        </div>
                        <div class="ml-auto">
                            <a class="u-link-v5 g-color-black--hover g-font-weight-600 g-font-size-12 text-uppercase" href="#">Reply</a>
                        </div>
                    </div>

                    <p>We get it, you're busy and it's important that someone keeps up with marketing and driving people to your brand. We've got you covered.</p>

                    <ul class="list-inline my-0">
                        <li class="list-inline-item g-mr-20">
                            <a class="g-color-gray-dark-v5 g-color-black--hover g-text-underline--none--hover" href="#">
                                <i class="icon-medical-022 u-line-icon-pro g-pos-rel g-top-1 g-mr-3"></i> 0
                            </a>
                        </li>
                        <li class="list-inline-item g-mr-20">
                            <a class="g-color-gray-dark-v5 g-color-black--hover g-text-underline--none--hover" href="#">
                                <i class="icon-finance-206 u-line-icon-pro g-pos-rel g-top-1 g-mr-3"></i> 0
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- End Comments -->
        </div>
    </div>
</div>
    <!-- Comments Form -->
<div class="media-md align-items-center g-mb-30 container-fluid">
    <div class="col-md-12">
        <form>
            <div class="g-mb-30">
                <textarea class="form-control g-bg-secondary g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-py-13 g-px-15" rows="5" placeholder="Your message..."></textarea>
            </div>
            <div class="d-flex align-items-center">
                <button class="btn u-btn-blue g-font-weight-600 g-font-size-12 text-uppercase g-py-12 g-px-25 mr-4" type="submit" role="button">Submit Message</button>
            </div>
        </form>
    </div>
</div>
    <!-- End Comments Form -->

KUBOnlinePRPM/Views/PM/ProjectDetail.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Breadcrumb-v1 -->
<div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20 g-mb-30">
    <ul class="u-list-inline g-color-gray-dark-v6">
        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="~/">Home</a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
        </li>
        @*<li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="~/PM">Project Monitoring</a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
        </li>*@
        <li class="list-inline-item">
            <span class="g-valign-middle">Morlot Highway</span>
        </li>
    </ul>
</div>
<!-- End Breadcrumb-v1 -->
<ul class="nav u-nav-v4-1 u-nav-primary" role="tablist" data-target="nav-4-1-primary-hor-center" data-tabs-mobile-type="slide-up-down" data-btn-classes="btn btn-md btn-block u-btn-outline-primary">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#nav-4-1-primary-hor-center--Overview" role="tab">Overview</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Schedules" role="tab">Schedules</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Finance" role="tab">Finance</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--DO" role="tab">Delivery Order</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Issues" role="tab">Issues</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Report" role="tab">Report</a>
    </li>   
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Files" role="tab">Files</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Conversation" role="tab">Conversation</a>
    </li>
</ul>
<div id="nav-4-1-primary-hor-center" class="tab-content g-pt-20 g-mb-40 g-brd--black g-bg-white">
    <div class="tab-pane fade show active" id="nav-4-1-primary-hor-center--Overview" role="tabpanel">
        @{ Html.RenderAction("ProjectOverview", "PM"); }
    </div>
    <div class="tab-pane fade" id="nav-4-1-primary-hor-center--Schedules" role="tabpanel">
        @{ Html.RenderAction("ProjectSchedules", "PM"); }       
    </div>
    <div class="tab-pane fade" id="nav-4-1-primary-hor-center--Finance" role="tabpanel">
        @{ Html.RenderAction("ProjectFinance", "PM"); }
    </div>
    <div class="tab-pane fade" id="nav-4-1-primary-hor-center--DO" role="tabpanel">
        @{ Html.RenderAction("ProjectDO", "PM"); }
    </div>
    <div class="tab-pane fade" id="nav-4-1-primary-hor-center--Issues" role="tabpanel">
        @{ Html.RenderAction("ProjectIssues", "PM"); }        
    </div>
    <div class="tab-pane fade g-mb-30" id="nav-4-1-primary-hor-center--Report" role="tabpanel">
        @{ Html.RenderAction("ProjectReport", "PM"); }        
    </div>
    <div class="tab-pane fade" id="nav-4-1-primary-hor-center--Files" role="tabpanel">
        @{ Html.RenderAction("ProjectFiles", "PM"); }        
    </div>   
    <div class="tab-pane fade" id="nav-4-1-primary-hor-center--Conversation" role="tabpanel">
        @{ Html.RenderAction("ProjectConversation", "PM"); }        
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var IssuesChart = new CanvasJS.Chart("IssuesChart", {
                animationEnabled: true,
                theme: "light2",
                data: [
                {
                    type: "pie",                   
                    startAngle: -20,
                    showInLegend: false,
                    dataPoints: [
                        { y: 70, label: "Open" },
                        { y: 30, label: "Closed" }
                    ],

                    //You can add dynamic data from the controller as shown below. Check the controller and uncomment the line which generates dataPoints.
                    //dataPoints: @Html.Raw(ViewBag.DataPoints),
                }
                ]
            });
            IssuesChart.render();

            var TaskChart = new CanvasJS.Chart("TaskChart", {
                animationEnabled: true,
                theme: "light2",
                data: [
                {
                    type: "pie",
                    startAngle: -20,
                    showInLegend: false,
                    dataPoints: [
                        { y: 170, label: "In Progress" },
                        { y: 30, label: "Not Started" },
                        { y: 130, label: "Completed" },
                        { y: 30, label: "Overdue" }
                    ],

                    //You can add dynamic data from the controller as shown below. Check the controller and uncomment the line which generates dataPoints.
                    //dataPoints: @Html.Raw(ViewBag.DataPoints),
                }
                ]
            });
            TaskChart.render();
        });
    </script>
    }