KUBOnlinePRPM/Controllers/Admin/UsersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KUBOnlinePRPM.Models;
using KUBOnlinePRPM.ViewModel;
using KUBOnlinePRPM.Service;

namespace KUBOnlinePRPM.Controllers.Admin
{
    public class UsersAdminController : DBLogicController
    {
        private KUBOnlinePREntities db = new KUBOnlinePREntities();
        private PRService PRService = new PRService();

        // GET: UsersAdmin
        public async Task<ActionResult> Heirarchy()
        {
            var users = PRService.populateUserList();
            return View(users);
        }

        // GET: UsersAdmin
        public async Task<ActionResult> Index()
        {
            var users = db.Users.Include(u => u.Customer).Include(x => x.Users_Roles);

            foreach(User u in users.ToList())
            {
                Console.WriteLine(u);
            }
            return View(await users.ToListAsync());
        }

        // GET: UsersAdmin/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: UsersAdmin/Create
        public ActionResult Create()
        {
            ViewBag.companyId = new SelectList(db.Customers, "custId", "name");
            return View();
        }

        // POST: UsersAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "uuid,userId,companyId,createByUserId,createDate,modifiedByUserId,modifiedDate,userName,password,passwordReset,passwordModifiedDate,reminderQueryQuestion,reminderQueryAnswer,emailAddress,firstName,lastName,employeeNo,jobTitle,loginDate,loginLatLng,loginAddress,lastLoginDate,lastFailedLoginDate,failedLoginAttempts,lockout,lockoutDate,status,telephoneNo,address,extensionNo,superiorId")] User user)
        {
            if (ModelState.IsValid)
            {
                user.uuid = System.Guid.NewGuid();
                user.password = BCrypt.HashPassword(user.password, BCrypt.GenerateSalt(12));
                db.Users.Add(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.companyId = new SelectList(db.Customers, "custId", "name", user.companyId);
            return View(user);
        }

        // GET: UsersAdmin/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            if (user.companyId == 2)
            {
                var InitApproverKUBM = (from m in db.Users
                                        join n in db.Users_Roles on m.userId equals n.userId
                                        where n.roleId == "R02" && m.childCompanyId != null && m.userId == id
                                        select new
                                        {
                                            userId = m.userId,
                                            firstName = m.userName,

                                        }).FirstOrDefault();
                var checkHOD = (from m in db.Users
                                join n in db.Users_Roles on m.userId equals n.userId
                                where n.roleId == "R02" && m.userId == id
                                select new
                                {
                                    userId = m.userId,
                                    firstName = m.userName,

                                }).FirstOrDefault();
                ViewBag.childCompanyId = InitApproverKUBM;
                ViewBag.HOD = checkHOD;
            }
            
            ViewBag.companyId = new SelectList(db.Customers, "custId", "name", user.companyId);
            ViewBag.superiorId = new SelectList(db.Users, "userId", "firstName", user.superiorId);
            ViewBag.roleList = db.Roles.Select(x => new UserRoleViewModel{ roleId = x.roleId , roleName = x.name});
            return View(user);
        }

        // POST: UsersAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "userId,companyId,createByUserId,createDate,modifiedByUserId,modifiedDate,userName,password,passwordReset,passwordModifiedDate,reminderQueryQuestion,reminderQueryAnswer,emailAddress,firstName,lastName,employeeNo,jobTitle,loginDate,loginLatLng,loginAddress,lastLoginDate,lastFailedLoginDate,failedLoginAttempts,lockout,lockoutDate,status,telephoneNo,address,extensionNo")] User user)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(user).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.companyId = new SelectList(db.Customers, "custId", "name", user.companyId);
        //    return View(user);
        //}

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditUser(int? id)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Entry(user).State = EntityState.Modified;
            //    await db.SaveChangesAsync();
            //    return RedirectToAction("Index");
            //}
            //ViewBag.companyId = new SelectList(db.Customers, "custId", "name", user.companyId);
            //return View(user);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var studentToUpdate = await db.Users.FindAsync(id);
            //ToDo add "childCompanyId" in string[] and add new department ddl for KUBM user to select from
            if (TryUpdateModel(studentToUpdate, "",
               new string[] { "companyId", "userName", "emailAddress", "firstName", "lastName", "employeeNo", "jobTitle", "status", "telephoneNo", "address", "extensionNo", "superiorId" }))
            {
                try
                {
                    await db.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(studentToUpdate);
        }

        // GET: UsersAdmin/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: UsersAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            User user = await db.Users.FindAsync(id);
            db.Users.Remove(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KUBOnlinePRPM/Views/UsersAdmin/Create.cshtml
@model KUBOnlinePRPM.Models.User

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.companyId, "companyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("companyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.companyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.employeeNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.employeeNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.employeeNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jobTitle, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.telephoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telephoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telephoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.extensionNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.extensionNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.extensionNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KUBOnlinePRPM/Views/UsersAdmin/Delete.cshtml
@model KUBOnlinePRPM.Models.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.uuid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.uuid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createByUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createByUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modifiedByUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modifiedByUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.passwordReset)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passwordReset)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.passwordModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passwordModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reminderQueryQuestion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reminderQueryQuestion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reminderQueryAnswer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reminderQueryAnswer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.employeeNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employeeNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.loginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.loginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.loginLatLng)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.loginLatLng)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.loginAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.loginAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastLoginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastLoginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastFailedLoginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastFailedLoginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.failedLoginAttempts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.failedLoginAttempts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lockout)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lockout)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lockoutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lockoutDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telephoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telephoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.extensionNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.extensionNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KUBOnlinePRPM/Views/UsersAdmin/Heirarchy.cshtml
@model KUBOnlinePRPM.Service.HeirarchyModel

@{
    ViewBag.Title = "Heirarchy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Users Heirarchy</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                Super Admin
            </th>
            <th>
                Head Of GPSS
            </th>
        </tr>

    </thead>
    <tbody>
        <tr>
            <td>
                <ol>
                    @foreach (var item in Model.SuperAdmin)
                    {
                        if (Model.SuperAdmin != null)
                        {
                            <li>@Html.ActionLink(item.firstName + ' ' + item.lastName, "Edit", "UsersAdmin", new { id = item.userId }, new { target = "_blank" })</li>
                        }
                    }
                </ol>
            </td>
            <td>
                <ol>
                    @foreach (var item in Model.HeadOfGPSS)
                    {
                        if (Model.HeadOfGPSS != null)
                        {
                            <li>@Html.ActionLink(item.firstName + ' ' + item.lastName, "Edit", "UsersAdmin", new { id = item.userId }, new { target = "_blank" })</li>
                        }
                    }
                </ol>
            </td>
        </tr>
    </tbody>

        </table>

<h5>Users</h5>

@foreach (var member in Model.Members)
{
    <h3>@member.SubsidiaryName</h3>



    <table class="table table-light table-striped">
        <thead>
            <tr>
                <th>
                    Type
                </th>
                <th>
                    Names
                </th>
            </tr>

        </thead>
        <tbody>
            <tr>
                @if (member.SubsidiaryName == "KUBM")
                {
                    <td>
                        GMD
                    </td>
                }
                else
                {
                    <td>
                        HOC
                    </td>
                }

                <td>
                    <ol>
                        @foreach (var x in member.HOCs)
                        {
                            <li>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</li>
                        }
                    </ol>
                </td>
            </tr>

            <tr>
                <td>
                    IT
                </td>
                <td>
                    @if (member.ITs.Count > 0)
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Username
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var x in member.ITs)
                            {
                                <tr>
                                    <td>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</td>
                                </tr>
                            }
                        </table>
                    }
                </td>
            </tr>

            <tr>
                <td>
                    PMO
                </td>
                <td>
                    @if (member.PMOs.Count > 0)
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Username
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var x in member.PMOs)
                            {
                                <tr>
                                    <td>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</td>
                                </tr>
                            }
                        </table>
                    }
                </td>
            </tr>

            <tr>
                <td>
                    HSE
                </td>
                <td>
                    @if (member.HSEs.Count > 0)
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Username
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var x in member.HSEs)
                            {
                                <tr>
                                    <td>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</td>
                                </tr>
                            }
                        </table>
                    }
                </td>
            </tr>

            <tr>
                <td>
                    Admin
                </td>
                <td>
                    @if (member.Admin.Count > 0)
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Username
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var x in member.Admin)
                            {
                                <tr>
                                    <td>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</td>
                                </tr>
                            }
                        </table>
                    }
                </td>
            </tr>

            <tr>
                <td>
                    Finance
                </td>
                <td>
                    @if (member.Finance.Count > 0)
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Username
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var x in member.Finance)
                            {
                                <tr>
                                    <td>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</td>
                                </tr>
                            }
                        </table>
                    }
                </td>
            </tr>

            <tr>
                <td>
                    Team Leader & HOD
                </td>
                <td>
                    @if (member.HODs.Count > 0)
                    {
                        <ol>
                            @foreach (var x in member.HODs)
                            {
                                <li>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</li>
                            }
                        </ol>
                    }
                </td>
            </tr>

            <tr>
                <td>
                    Procurement
                </td>
                <td>
                    @if (member.Procurements.Count > 0)
                    {
                        <ol>
                            @foreach (var x in member.Procurements)
                            {
                                <li>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</li>
                            }
                        </ol>
                    }
                </td>

            </tr>

            <tr>
                <td>
                    Requestors
                </td>
                <td>


                    @if (member.Requestors.Count > 0)
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Username
                                    </th>
                                    <th>
                                        HOD
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var x in member.Requestors)
                            {
                                <tr>
                                    <td>@Html.ActionLink(@x.firstName + ' ' + @x.lastName, "Edit", "UsersAdmin", new { id = @x.userId }, new { target = "_blank" })</td>
                                    @if (x.superiorId != null)
                                    {
                                        <td>@Html.ActionLink(@x.superiorFirstName, "Edit", "UsersAdmin", new { id = @x.superiorId }, new { target = "_blank" })</td>
                                    }
                                    else
                                    {
                                        <td></td>
                                    }
                                </tr>
                            }
                        </table>
                    }
                </td>
            </tr>
        </tbody>

    </table>
}

<br /><br /><br />