KUBOnlinePRPM/Controllers/PRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RazorEngine;
using RazorEngine.Templating;
using KUBOnlinePRPM.Models;
using System.IO;
using KUBOnlinePRPM.Controllers;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.DirectoryServices;
using System.DirectoryServices.Protocols;
using System.DirectoryServices.ActiveDirectory;
using System.DirectoryServices.AccountManagement;
using System.Net;
using System.Globalization;
using KUBOnlinePRPM.Service;
using System.Diagnostics;
using System.Net.Mail;
using System.Collections;
using System.Web.Security;
using System.Web.Routing;
using System.Data.Entity.Validation;
using System.Data.Entity;
using System.Configuration;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace KUBOnlinePRPM.Controllers
{
    public class DecimalModelBinder : IModelBinder
    {
        public object BindModel(ControllerContext controllerContext,
            ModelBindingContext bindingContext)
        {
            ValueProviderResult valueResult = bindingContext.ValueProvider
                .GetValue(bindingContext.ModelName);
            ModelState modelState = new ModelState { Value = valueResult };
            object actualValue = null;
            try
            {
                actualValue = Convert.ToDecimal(valueResult.AttemptedValue,
                    CultureInfo.CurrentCulture);
            }
            catch (FormatException e)
            {
                modelState.Errors.Add(e);
            }

            bindingContext.ModelState.Add(bindingContext.ModelName, modelState);
            return actualValue;
        }
    }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, Inherited = true, AllowMultiple = false)]
    public class CheckSessionOutAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName.ToLower();
            if (!controllerName.Contains("home"))
            {
                HttpSessionStateBase session = filterContext.HttpContext.Session;
                var user = session["Username"]; //Key 2 should be User or UserName
                if (((user == null) && (!session.IsNewSession)) || (session.IsNewSession))
                {
                    FormsAuthentication.SignOut();
                    filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary {
                        { "action", "Index" },
                        { "controller", "Home" },
                        { "returnUrl", filterContext.HttpContext.Request.RawUrl}
                    });

                    return;
                }
                base.OnActionExecuting(filterContext);
            }
        }
    }

    public class ValidateAjaxAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (!filterContext.HttpContext.Request.IsAjaxRequest())
                return;

            var modelState = filterContext.Controller.ViewData.ModelState;
            var PRModel = filterContext.ActionParameters.Values.FirstOrDefault() as PRModel;
            var POModel = filterContext.ActionParameters.Values.FirstOrDefault() as POModel;
            if (PRModel != null)
            {
                if (PRModel.NewPRForm.StatusId == "PR02")
                {
                    if (PRModel.NewPRForm.VendorId == null)
                    {
                        modelState.AddModelError("NewPRForm.VendorId", "Please select vendor company name.");
                    }
                    for (int i = 0; i < PRModel.NewPRForm.PRItemListObject.Count; i++)
                    {
                        if (PRModel.NewPRForm.PRItemListObject[i].ItemTypeId == null)
                        {
                            modelState.AddModelError("NewPRForm.PRItemListObject[" + (i + 1) + "].ItemTypeId", "Please insert Item Type");
                        }
                        if (PRModel.NewPRForm.PRItemListObject[i].CodeId == null)
                        {
                            modelState.AddModelError("NewPRForm.PRItemListObject[" + (i + 1) + "].CodeId", "Please insert Item Code");
                        }
                        if (PRModel.NewPRForm.PRItemListObject[i].UnitPrice == null)
                        {
                            modelState.AddModelError("NewPRForm.PRItemListObject[" + (i + 1) + "].UnitPrice", "Please insert unit price (RM)");
                        }
                        if (PRModel.NewPRForm.PRItemListObject[i].TaxCodeId == null)
                        {
                            modelState.AddModelError("NewPRForm.PRItemListObject[" + (i + 1) + "].TaxCodeId", "Please select SST code");
                        }
                        if (PRModel.NewPRForm.PRItemListObject[i].UoMId == null)
                        {
                            modelState.AddModelError("NewPRForm.PRItemListObject[" + (i + 1) + "].UoMId", "Please select UOM code");
                        }
                    }
                    //todo: add other field validation
                }
                if (PRModel.NewPRForm.StatusId == "PR10" && PRModel.FinalApproverId == 0)
                {
                    modelState.AddModelError("FinalApproverId", "Please select final approver name.");
                }
                if (PRModel.NewPRForm.PaperRefNo != null && PRModel.PaperRefNoFile == null)
                {
                    modelState.AddModelError("PaperRefNoFileName", "GMD paper attachment needed.");
                }
                if (PRModel.NewPRForm.BidWaiverRefNo != null && PRModel.BidWaiverRefNoFile == null)
                {
                    modelState.AddModelError("BidWaiverRefNoFileName", "Bid Waiver attachment needed");
                }
                if (PRModel.NewPRForm.PaperRefNo == null && PRModel.PaperRefNoFile != null)
                {
                    modelState.AddModelError("NewPRForm.PaperRefNo", "GMD paper ref no needed.");
                }
                if (PRModel.NewPRForm.BidWaiverRefNo == null && PRModel.BidWaiverRefNoFile != null)
                {
                    modelState.AddModelError("NewPRForm.BidWaiverRefNo", "Bid Waiver ref no needed");
                }
                if (PRModel.PaperRefNoFile != null && Path.GetExtension(PRModel.PaperRefNoFile.FileName) != ".pdf")
                {
                    modelState.AddModelError("PaperRefNoFileName", "Only pdf file accepted.");
                }
                if (PRModel.BidWaiverRefNoFile != null && Path.GetExtension(PRModel.BidWaiverRefNoFile.FileName) != ".pdf")
                {
                    modelState.AddModelError("BidWaiverRefNoFileName", "Only pdf file accepted.");
                }
            }
            if (POModel != null)
            {
            }
            if (!modelState.IsValid)
            {
                var errorModel =
                        from x in modelState.Keys
                        where modelState[x].Errors.Count > 0
                        select new
                        {
                            key = x,
                            errors = modelState[x].Errors.
                                                          Select(y => y.ErrorMessage).
                                                          ToArray()
                        };
                filterContext.Result = new JsonResult()
                {
                    Data = new
                    {
                        success = false,
                        exception = false,
                        data = errorModel
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
                //filterContext.HttpContext.Response.StatusCode = 200;
            }
        }
    }

    public class PRController : DBLogicController
    {
        private KUBOnlinePREntities db = new KUBOnlinePREntities();
        private KUBHelper KUBHelper = new KUBHelper();
        private PRService PRService = new PRService();

        [CheckSessionOut]
        public ActionResult Index()
        {
            //var testList = db1.KUB_Telekomunikasi_Sdn_Bhd_Contact.ToList();
            //ActiveDirectoryContext context = new ActiveDirectoryContext();
            //context.Configuration.UseDatabaseNullSemantics = true;
            //var query = from line in context.User select line;            
            return View();
        }

        public JsonResult DashboardPurchaseRequisition()
        {
            var sql = "SELECT 'Open'        AS [description], " +
                               "Sum(quantity) AS quantity " +
                        "FROM   (SELECT m.status      AS [description], " +
                                       "Count(n.prid) AS quantity " +
                                "FROM   prstatus m " +
                                       "LEFT JOIN purchaserequisition n " +
                                              "ON ( m.statusid = n.statusid ) " +
                                "WHERE  m.statusid <> 'PR08' " +
                                       "AND m.statusid <> 'PR06' " +
                                       "AND m.statusid <> 'PR14' " +
                                       "AND m.statusid <> 'PR07' " +
                                "GROUP  BY m.status) AS T " +
                        "UNION " +
                        "SELECT TOP 3 m.status      AS [description], " +
                                     "Count(n.prid) AS quantity " +
                        "FROM   prstatus m " +
                               "LEFT JOIN purchaserequisition n " +

KUBOnlinePRPM/Views/PR/BPRFiles.cshtml
this is bpr files

KUBOnlinePRPM/Views/PR/BPRTabs.cshtml
@model KUBOnlinePRPM.Models.PRModel

<!-- Breadcrumb-v1 -->
<div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20 g-mb-30">
    <ul class="u-list-inline g-color-gray-dark-v6">
        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="~/PR">Purchase Requisition</a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
        </li>
        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="~/PR/PRList?type=Blank">Listings</a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
        </li>
        <li class="list-inline-item">
            <span class="g-valign-middle">@Model.NewPRForm.PRNo</span>
        </li>
    </ul>
</div>
<!-- End Breadcrumb-v1 -->
<ul class="nav u-nav-v4-1 u-nav-primary" role="tablist" data-target="nav-4-1-primary-hor-center" data-tabs-mobile-type="slide-up-down" data-btn-classes="btn btn-md btn-block u-btn-outline-primary">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#nav-4-1-primary-hor-center--PRDetails" role="tab">PR Details</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--BPRPOList" role="tab">PO List</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Conversations" role="tab">Conversations</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#nav-4-1-primary-hor-center--Files" role="tab">Files</a>
    </li>
</ul>
<div id="nav-4-1-primary-hor-center" class="tab-content g-pa-20--md g-mb-40 g-brd--black g-bg-white">
    <div class="tab-pane fade show active" id="nav-4-1-primary-hor-center--PRDetails" role="tabpanel">
        <div class="container-fluid">
            @{ Html.RenderAction("PRDetails", "PR"); }
        </div>
    </div>
    <div class="tab-pane fade show" id="nav-4-1-primary-hor-center--BPRPOList" role="tabpanel">
        <div class="container-fluid">
            @{ Html.RenderAction("BPRPOList", "PR"); }
        </div>
    </div>
    <div class="tab-pane fade show" id="nav-4-1-primary-hor-center--Conversations" role="tabpanel">
        <div class="container-fluid">
            @{ Html.RenderAction("PRConversations", "PR"); }
        </div>
    </div>
    <div class="tab-pane fade show" id="nav-4-1-primary-hor-center--Conversations" role="tabpanel">
        <div class="container-fluid">
            @{ Html.RenderAction("PRFiles", "PR"); }
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var BPRItemDetailsTable;
        var UrlBPRPODetails = "@Url.Action("PODetails", "PO")";
        var BPRPOListTable;
        var touchtime = 0;
    </script>
    <script src="~/Scripts/PRDetails.js"></script>
    <script src="~/Scripts/BPRPOList.js"></script>
    @*<script src="~/Scripts/PRConversations.js"></script>*@
}

KUBOnlinePRPM/Views/PR/Index.cshtml
@*<div class="g-pa-20">*@
<!-- Metrics 8 -->
<div class="row container-fluid g-mb-20">
    <div class="media-body align-self-center text-left">
        <h3 class="g-font-weight-600 g-font-size-30 g-color-black">Summary</h3>
    </div>
    @if (Session["ifRequestor"] != null)
    {
        <div class="media-body align-self-center text-right">
            <a class="btn btn-xl u-btn-lightblue-v3 g-font-size-default g-ml-10" href="~/PR/NewPR?type=Generic">
                NEW +
            </a>
        </div>
    }
    </div>
<div class="row">
    <div class="col-sm-4 col-lg-4 col-xl-4 g-mb-30">
        <!-- Panel -->
        <div class="card h-100 g-brd-gray-light-v7 rounded">
            <div class="card-block g-font-weight-300 g-pa-20">
                <div class="media-body align-self-center">
                    <h4 class="g-font-size-24 g-font-weight-600 g-color-gray-dark-v6 mb-0">Purchase Requisition</h4>
                </div>
                <div class="media align-self-center">
                    <canvas id="chart_pr" height="350"></canvas>
                </div>
            </div>
        </div>
        <!-- End Panel -->
    </div>

    <div class="col-sm-4 col-lg-4 col-xl-4 g-mb-30">
        <!-- Panel -->
        <div class="card h-100 g-brd-gray-light-v7 rounded">
            <div class="card-block g-font-weight-300 g-pa-20">
                <div class="media-body align-self-center">
                    <h4 class="g-font-size-24 g-font-weight-600 g-color-gray-dark-v6 mb-0">Purchase Order</h4>
                </div>
                <div class="media align-self-center">

                    <canvas id="chart_po" height="350"></canvas>

                </div>
            </div>
        </div>
        <!-- End Panel -->
    </div>

    <div class="col-sm-4 col-lg-4 col-xl-4 g-mb-30">
        <!-- Panel -->
        <div class="card h-100 g-brd-gray-light-v7 rounded">
            <div class="card-block g-font-weight-300 g-pa-20">
                <div class="media-body align-self-center">
                    <h4 class="g-font-size-24 g-font-weight-600 g-color-gray-dark-v6 mb-0">Open PO</h4>
                </div>
                <div class="media align-self-center">

                    <canvas id="chart_open_po" height="350"></canvas>

                </div>
            </div>
        </div>
        <!-- End Panel -->
    </div>
</div>
@*<div class="row">*@
<div class="container-fluid g-mb-20">
    @{ Html.RenderAction("Index", "Notification"); }
</div>
@*</div>*@
<!-- Metrics 8 -->
@*</div>*@

@section scripts {
    <script>
        var width;
        var height;
        var PRChart;
        var $window = $(window);
        var $pane = $('#pane1');
        var UrlPRList = "@Url.Action("PRList", "PR")";
        var UrlPOList = "@Url.Action("POList", "PO")";
        var UrlDashboardPurchaseRequisition = "@Url.Action("DashboardPurchaseRequisition", "PR")";
        var UrlDashboardPurchaseOrder = "@Url.Action("DashboardPurchaseOrder", "PR")";
        var UrlDashboardOpenPO = "@Url.Action("DashboardOpenPO", "PR")";
        var NotificationTable;
        var UrlPRTabs = "@Url.Action("ViewPRTabs", "PR")";
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
    <script src="~/Scripts/PR.js"></script>
    <script src="~/Scripts/Notification.js"></script>
}

KUBOnlinePRPM/Views/PR/PRFiles.cshtml
@model KUBOnlinePRPM.Models.PRModel

@*<div class="row container-fluid">
        <div class="media-body align-self-center text-right">
            <a href="~/PR/PRForm">
                <span class="u-icon-v1 g-color-blue">
                    <i class="icon-printer"></i>
                </span>
            </a>
        </div>
    </div>*@
@using (Html.BeginForm("PRFiles", "PR", FormMethod.Post, new { @id = "PRFiles", @class = "container-fluid g-mb-40" }))
{
    <div class="col-xs-12 g-mb-30 g-mt-40">
        <table id="PRFileTable" class="table table-striped table-bordered dt-responsive table-hover" style="width:100%">
            <thead>
                <tr>
                    <th class="d-none"></th>
                    <th class="all">
                        <div class="media">
                            <div class="d-flex align-self-center">File Name</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Extension</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Description</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Upload By</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Upload Date</div>
                        </div>
                    </th>
                    <th class="all">
                        <div class="media">
                            <div class="d-flex align-self-center">Action</div>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @{
                            int i = 1;
                            int FileEntryId = 0;
                            foreach (var item in Model.PRDocListObject)
                            {
                                string filename = item.FileName.Replace("\\", ",");
                                string filename1 = filename.Split(',')[filename.Split(',').Length - 1].ToString();
                        <tr>
                            <td class="d-none">@Html.DisplayFor(modelItem => item.fileEntryId)</td>
                            <td>
                                @Html.DisplayFor(modelItem => filename1)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Extension)
                            </td>
                             <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.uploadUserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.uploadDate)
                            </td>
                            <td>
                                <a id="DownloadFile" class="btn btn-md text-white u-btn-blue g-mb-5" href="@Url.Action("FileDownload", "PR", new { id = item.fileEntryId })">Download</a>
                                @*@Html.ActionLink("Download", "FileDownload", "PR", null, null, "anchor-point", new { id = item.fileEntryId }, null)*@
                                @{
                                    FileEntryId = item.fileEntryId;
                                }
                                <a id="@FileEntryId" class="DeleteFile btn btn-md text-white u-btn-blue g-mb-5">Delete</a>
                            </td>
                        </tr>
                        i++;
                }
                }
            </tbody>
        </table>
    </div>
    <div class="d-none" id="FileEntryId"></div>
    <div class="col-md-12 col-sm-12">
        <div class="row g-mb-20">
            <div class="col-md-2 col-sm-2 formfield">
                <label class="g-mb-10" for="UploadFileInput">Upload File here: </label>
            </div>
            <div class="col-md-6 col-sm-6 input-group u-file-attach-v1 g-brd-gray-light-v2">
                <input id="UploadFileInput" class="form-control form-control-md g-rounded-4" placeholder="" readonly="" type="text" value="@Model.UploadFile">

                <div class="input-group-append">
                    <button class="btn btn-md u-btn-blue rounded-0" type="submit">Browse</button>
                    <input name="UploadFile" type="file">
                </div>
            </div>
        </div>
        <div class="row g-mb-20">
            <div class="col-md-2 col-sm-2 formfield">
                <span>File Description</span>
            </div>
            <div class="d-flex col-md-6 col-sm-6">
                @Html.TextBoxFor(m => m.FileDescription, new { @id = "FileDescription", @class = "form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-20 g-px-14 g-py-10", @type = "text" })
            </div>
        </div>
        <div class="row">
            @*<div class="col-md-9 col-sm-8"></div>*@
            <div class="col-md-2 offset-md-6 col-sm-4 offset-sm-8">
                <div class="media float-md-right">
                    <div class="d-flex u-main-nav--push-right text-right">
                            <a id="UploadFile" class="UploadFile btn btn-md text-white u-btn-blue g-mr-5 g-mb-15">UPLOAD FILE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
        }

    <div id="UploadProgressModal" class="text-left g-max-width-600 g-bg-white g-overflow-y-auto g-pa-20" style="display: none;">
        <button type="button" class="close" onclick="Custombox.modal.close();">
            <i class="hs-icon hs-icon-close"></i>
        </button>
        <div class="row" id="uploadProgress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                0% Complete
            </div>
        </div>
    </div>

KUBOnlinePRPM/Views/PR/PRList.cshtml
@model KUBOnlinePRPM.Models.PRModel

<!-- Breadcrumb-v1 -->
<div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
    <ul class="u-list-inline g-color-gray-dark-v6">
        <li class="list-inline-item g-mr-10">
            <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="~/PR">Purchase Requisition</a>
            <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
        </li>
        <li class="list-inline-item">
            <span class="g-valign-middle">Purchase Requisition - Listings</span>
        </li>
    </ul>
</div>
<!-- End Breadcrumb-v1 -->
<div class="media-md align-items-center g-pa-20">
    <div class="d-flex g-mb-0--md g-pa-10">
        <h3 class="g-font-weight-300 g-font-size-20 g-color-black mb-0">Purchase Requisition List (@Model.Type)</h3>
    </div>
</div>
<div class="g-bg-white g-brd-1 g-brd-gray-light-v3 g-brd-style-solid rounded g-mb-40">
    <div class="container-fluid g-pa-20">
        <table id="PRListTable" class="table table-striped table-bordered dt-responsive table-hover" style="width:100%">
            <thead>
                <tr>
                    <th class="d-none"></th>
                    <th class="g-first-child all">
                        <div class="media">
                            <div class="d-flex align-self-center">PR No.</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">PR Date</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Requestor Name</div>
                        </div>
                    </th>
                    <th class="tablet">
                    <div class="media">
                        <div class="d-flex align-self-center">Requestor Department</div>
                    </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Company Name</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Vendor Company</div>
                        </div>
                    </th>
                    <th class="desktop">
                        <div class="media">
                            <div class="d-flex align-self-center">Amount Required (RM)</div>
                        </div>
                    </th>
                    <th class="tablet">
                        <div class="media">
                            <div class="d-flex align-self-center">PR Aging</div>
                        </div>
                    </th>
                    <th class="all">
                        <div class="media">
                            <div class="d-flex align-self-center">Status</div>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model.PRListObject)
                    {
                <tr>
                    <td class="d-none">@Html.DisplayFor(modelItem => item.PRId)</td>
                    <td class="all"><a class="PRDetailsButton btn btn-md u-btn-blue g-mr-5 g-mb-15">@Html.DisplayFor(modelItem => item.PRNo)</a></td>
                    <td class="desktop">@Html.DisplayFor(modelItem => item.PRDate)</td>
                    <td class="desktop">@Html.DisplayFor(modelItem => item.RequestorName)</td>
                    <td class="tablet">@Html.DisplayFor(modelItem => item.DeptName)</td>
                    <td class="desktop">@Html.DisplayFor(modelItem => item.CompanyName)</td>
                    <td class="desktop">@Html.DisplayFor(modelItem => item.VendorCompany)</td>
                    <td class="desktop">@Html.DisplayFor(modelItem => item.AmountRequired)</td>
                    <td class="tablet">@Html.DisplayFor(modelItem => item.PRAging)</td>
                    @if (item.Status == "Reject" || item.Status == "Cancel")
                    {
                        <td class="all">
                            <div class="d-inline-block">
                                <span class="d-flex align-items-center justify-content-center u-tags-v1 g-brd-around g-bg-white g-font-size-default g-color-gray-dark-v6 g-brd-white g-rounded-50 g-py-4 g-px-15">
                                    <span class="u-badge-v2--md g-pos-stc g-transform-origin--top-left g-bg-red g-mr-8"></span>
                                    @item.Status
                                </span>
                            </div>
                        </td>
                    }
                    else
                    {
                        <td class="all">
                            <div class="d-inline-block">
                                <span class="d-flex align-items-center justify-content-center u-tags-v1 g-brd-around g-bg-white g-font-size-default g-color-gray-dark-v6 g-brd-white g-rounded-50 g-py-4 g-px-15">
                                    <span class="u-badge-v2--md g-pos-stc g-transform-origin--top-left g-bg-red g-mr-8"></span>
                                    @item.Status
                                </span>
                            </div>
                        </td>
                    }
                </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var UrlPRTabs = "@Url.Action("ViewPRTabs", "PR")";
        var PRListTable;
        var PRType = "@Model.Type";
        var touchtime = 0;
    </script>
    <script src="~/Scripts/PRList.js"></script>
}