KUBOnlinePRPM/Controllers/POController.cs
using KUBOnlinePRPM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;
using KUBOnlinePRPM.Controllers;
using System.Data.Entity.Validation;
using System.IO;
using System.Configuration;
using System.Data.SqlClient;
using Microsoft.Reporting.WebForms;

namespace KUBOnlinePRPM.Controllers
{
    public class POController : DBLogicController
    {
        private KUBOnlinePREntities db = new KUBOnlinePREntities();
        // GET: PO
        [CheckSessionOut]
        public ActionResult Index()
        {
            return View();
        }

        [CheckSessionOut]
        public ActionResult NewPO(string type)
        {
            if (User.Identity.IsAuthenticated && Session["UserId"] != null)
            {
                POModel NewPO = new POModel
                {
                    UserId = Int32.Parse(Session["UserId"].ToString()),
                    Type = type
                };
                int PRId = Int32.Parse(Session["PRId"].ToString());
                POModel PODetail = new POModel();
                int PRCustId = (from m in db.PurchaseRequisitions
                                join n in db.Projects on m.ProjectId equals n.projectId
                                where m.PRId == PRId
                                select new
                                {
                                    CustId = n.custId
                                }).First().CustId;

                var PayToVendorQuery = (from m in db.Vendors
                                        where m.custId == PRCustId
                                        select new
                                        {
                                            VendorId = m.vendorId,
                                            VendorName = m.vendorNo + " - " + m.name,
                                            VendorNo = m.vendorNo,
                                        }).OrderBy(c => c.VendorNo).ThenBy(c => c.VendorName);
                var PaymentTermsCodeQuery = (from m in db.PaymentTerms
                                             where m.custId == PRCustId
                                             select new
                                             {
                                                 PaymentTermsId = m.paymentTermsId,
                                                 PaymentDescription = m.paymentCode + " - " + m.paymentDescription,
                                                 PaymentCode = m.paymentCode,
                                             }).OrderBy(c => c.PaymentCode).ThenBy(c => c.PaymentDescription);
                var LocationQuery = db.Locations.Select(m => new { LocationCodeId = m.locationId, LocationCode = m.locationCode, Address = m.locationAddress + m.locationCity }).OrderBy(m => m.LocationCode);
                var SpecReviewerQuery = db.Groups.Select(c => new GroupList { GroupId = c.groupId, GroupName = c.groupName }).OrderBy(c => c.GroupName);
                var PurchaserCodeQuery = db.Purchasers.Select(m => new { PurchaserCodeId = m.purchaserId, PurchaserCode = m.purchaserCode }).OrderBy(m => m.PurchaserCode);
                PODetail.UserId = Int32.Parse(Session["UserId"].ToString());
                PODetail.NewPOForm = (from a in db.PurchaseRequisitions
                                      join b in db.Users on a.PreparedById equals b.userId into s
                                      join d in db.Projects on a.ProjectId equals d.projectId
                                      join e in db.Vendors on a.VendorId equals e.vendorId into f
                                      join g in db.VendorStaffs on a.VendorStaffId equals g.staffId into l
                                      join h in db.PR_Items on a.PRId equals h.PRId
                                      join j in db.PopulateItemLists on h.codeId equals j.codeId into k
                                      from w in l.DefaultIfEmpty()
                                      from x in s.DefaultIfEmpty()
                                      from y in f.DefaultIfEmpty()
                                      from z in k.DefaultIfEmpty()
                                      where a.PRId == PRId
                                      select new NewPOModel()
                                      {
                                          PRNo = a.PRNo,
                                          ProjectId = a.ProjectId,
                                          ProjectName = d.projectName,
                                          //PaperRefNo = a.PaperRefNo,
                                          //ch = x.childCompanyId,
                                          VendorId = a.VendorId,
                                          VendorName = y.name,
                                          VendorCode = y.vendorNo,
                                          VendorQuoteNo = a.VendorQuoteNo,
                                          VendorEmail = w.vendorEmail,
                                          VendorStaffId = w.staffId,
                                          VendorContactNo = w.vendorContactNo,
                                          PreparedById = a.PreparedById,
                                          PRDate = a.PreparedDate,
                                          DiscountAmount = a.DiscountAmount,
                                          DiscountPerc = a.Discount_,
                                          TotalSST = a.TotalSST,
                                          SpecReviewerId = a.SpecsReviewerId,
                                          StatusId = "PO01"
                                      }).FirstOrDefault();

                PODetail.NewPOForm.POItemListObject = (from m in db.PR_Items.DefaultIfEmpty()
                                                       from n in db.PopulateItemLists.Where(x => m.codeId == x.codeId && m.itemTypeId == x.itemTypeId).DefaultIfEmpty()
                                                       join o in db.Projects on m.jobNoId equals o.projectId into p
                                                       join r in db.ItemTypes on m.itemTypeId equals r.itemTypeId into s
                                                       join u in db.JobTasks on m.jobTaskNoId equals u.jobTaskNoId into v
                                                       join x in db.TaxCodes on m.taxCodeId equals x.TaxCodeId into y
                                                       join a in db.UOMs on m.UoMId equals a.UoMId into b
                                                       from q in p.DefaultIfEmpty()
                                                       from t in s.DefaultIfEmpty()
                                                       from w in v.DefaultIfEmpty()
                                                       from z in y.DefaultIfEmpty()
                                                       from c in b.DefaultIfEmpty()
                                                       where m.PRId == PRId && m.outStandingQuantity != 0
                                                       select new POItemsTable()
                                                       {
                                                           ItemsId = m.itemsId,
                                                           DateRequired = m.dateRequired,
                                                           ItemTypeId = m.itemTypeId,
                                                           CodeId = m.codeId.Value,
                                                           ItemCode = n.Description,
                                                           Description = m.description,
                                                           CustPONo = m.custPONo,
                                                           Quantity = m.quantity,
                                                           OutStandingQuantity = m.outStandingQuantity.Value,
                                                           UoMId = m.UoMId,
                                                           UOM = c.UoMCode,
                                                           JobNoId = q.projectId,
                                                           JobNo = q.projectCode,
                                                           JobTaskNoId = m.jobTaskNoId,
                                                           JobTaskNo = w.jobTaskNo,
                                                           UnitPrice = m.unitPrice.Value,
                                                           TotalPrice = m.outStandingQuantity.Value * m.unitPrice.Value,
                                                           UnitPriceIncSST = m.unitPriceIncSST,
                                                           TotalPriceIncSST = m.outStandingQuantity.Value * m.unitPriceIncSST,
                                                           DimProjectId = m.dimProjectId,
                                                           DimDeptId = m.dimDeptId
                                                       }).ToList();

                decimal TotalExclSST = 0; decimal TotalIncSST = 0;
                foreach (var value in PODetail.NewPOForm.POItemListObject)
                {
                    TotalExclSST = TotalExclSST + value.TotalPrice;
                    TotalIncSST = TotalIncSST + value.TotalPriceIncSST.Value;
                }
                PODetail.NewPOForm.TotalExcSST = TotalExclSST;
                PODetail.NewPOForm.TotalIncSST = TotalIncSST;

                ViewBag.PayToVendorList = new SelectList(PayToVendorQuery.AsEnumerable(), "VendorId", "VendorName", PODetail.NewPOForm.PayToVendorId);
                ViewBag.PaymentTermsCodeList = new SelectList(PaymentTermsCodeQuery.AsEnumerable(), "PaymentTermsId", "PaymentDescription", PODetail.NewPOForm.PaymentTermsId);

KUBOnlinePRPM/Views/PO/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

KUBOnlinePRPM/Views/PO/POList.cshtml
@model KUBOnlinePRPM.Models.POModel

@if (Model.Type == "All")
{
    <!-- Breadcrumb-v1 -->
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20 g-mb-30">
        <ul class="u-list-inline g-color-gray-dark-v6">
            <li class="list-inline-item g-mr-10">
                <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="~/PR">Purchase Order</a>
                <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
            </li>
            <li class="list-inline-item">
                <span class="g-valign-middle">Purchase Order - Listings</span>
            </li>
        </ul>
    </div>
}
<!-- End Breadcrumb-v1 -->
<div class="media-md align-items-center g-pa-20">
    <div class="d-flex g-mb-0--md g-pa-10">
        <h3 class="g-font-weight-300 g-font-size-20 g-color-black mb-0">Purchase Order List</h3>
    </div>
</div>
<div class="g-bg-white g-brd-1 g-brd-gray-light-v3 g-brd-style-solid rounded g-mb-40">
    <div class="container-fluid g-pa-20">
        @if (Model.Type != "Blanket")
        {
            <table id="POListTable" class="table table-striped table-bordered dt-responsive table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th class="d-none">PO Id</th>
                        <th class="g-first-child all">
                            <div class="media">
                                <div class="d-flex align-self-center">PO No.</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">PO Date</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">PR No.</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">Company</div>
                            </div>
                        </th>
                        <th class="tablet">
                            <div class="media">
                                <div class="d-flex align-self-center">Requestor Name</div>
                            </div>
                        </th>
                        <th class="tablet">
                            <div class="media">
                                <div class="d-flex align-self-center">Vendor ID</div>
                            </div>
                        </th>
                        <th class="tablet">
                            <div class="media">
                                <div class="d-flex align-self-center">Vendor Name</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">Amount Required (RM)</div>
                            </div>
                        </th>
                        <th class="all">
                            <div class="media">
                                <div class="d-flex align-self-center">PO Aging (days)</div>
                            </div>
                        </th>
                        <th class="all">
                            <div class="media">
                                <div class="d-flex align-self-center">Status</div>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model.POListObject)
                        {
                            <tr>
                                <th class="d-none">@Html.DisplayFor(modelItem => item.POId)</th>
                                <td class="all">@Html.DisplayFor(modelItem => item.PONo)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.PODate)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.PRNo)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.Company)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.RequestedName)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.VendorId)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.VendorCompany)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.TotalPrice)</td>
                                <td class="all">@Html.DisplayFor(modelItem => item.POAging)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.Status)</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
        @if (Model.Type == "Blanket")
        {
            <table id="POListTable" class="table table-striped table-bordered dt-responsive table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th class="d-none">PO Id</th>
                        <th class="g-first-child all">
                            <div class="media">
                                <div class="d-flex align-self-center">PO No.</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">PO Date</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">Item</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">Quantity</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">Total Price (RM)</div>
                            </div>
                        </th>
                        <th class="all">
                            <div class="media">
                                <div class="d-flex align-self-center">PO Aging (days)</div>
                            </div>
                        </th>
                        <th class="desktop">
                            <div class="media">
                                <div class="d-flex align-self-center">Status</div>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model.POListObject)
                        {
                            <tr>
                                <th class="d-none">@Html.DisplayFor(modelItem => item.POId)</th>
                                <td class="all">@Html.DisplayFor(modelItem => item.PONo)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.PODate)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.POItem)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.Quantity)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.TotalPrice)</td>
                                <td class="all">@Html.DisplayFor(modelItem => item.POAging)</td>
                                <td class="desktop">@Html.DisplayFor(modelItem => item.Status)</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            if ((Session["ifRequestor"] != null || Session["ifProcurement"] != null) && Model.OutstandingQty != 0 && Model.StatusId == "PR06")
            {
                <div class="col-md-12 col-sm-12">
                    <div class="row">
                        @*<div class="col-md-9 col-sm-8"></div>*@
                        <div class="col-md-3 offset-md-9 col-sm-4 offset-sm-8">
                            <div class="media">
                                <div class="d-flex u-main-nav--push-right text-right">
                                    <div class="row">
                                        <a id="NewPO" href="~/PO/NewPO?type=Blanket" class="btn btn-md u-btn-blue g-mr-5 g-mb-15">NEW PO</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var UrlPODetails = "@Url.Action("ViewPODetails", "PO")";
        var POListTable;
        var POType = "@Model.Type";
        var touchtime = 0;
    </script>
    <script src="~/Scripts/POList.js"></script>
}